services:
  ramsey.uuid.factory:
    class: Ramsey\Uuid\UuidFactory
  id.generator.string:
    class: Vain\Id\Generator\Ramsey\RamseyAdapter
    arguments: ['@ramsey.uuid.factory']
  id.generator.string.random: '@id.generator.string'