imports:
#  - { resource: 'vendor/vain/core/config/di.yml' }

services:
  ramsey.uuid.factory:
    class: Ramsey\Uuid\UuidFactory
  id.generator.string:
    class: Vain\Id\Generator\Ramsey\RamseyAdapter
    arguments: ['@ramsey.uuid.factory']
  id.generator.random.string: '@id.generator.string'