services:
  ramsey.uuid.factory:
    class: Ramsey\Uuid\UuidFactory
  id.generator.string:
    class: Vain\Ramsey\RamseyIdGenerator
    arguments: ['@ramsey.uuid.factory']
  id.generator.string.random:
    alias: id.generator.string